actor_mode: hybrid
algorithm: blender
anneal_lr: true
batch_size: 7680
blend_ent_coef: 0.0
blend_function: softmax
blender_learning_rate: 0.00025
blender_mode: logic
capture_video: false
clip_coef: 0.1
clip_vloss: true
cuda: true
ent_coef: 0.01
env_id: Seaquest-v4
env_name: kangaroo
exp_name: train_blenderl
gae_lambda: 0.95
gamma: 0.99
joint_training: true
learning_rate: 0.00025
logic_learning_rate: 0.00025
max_grad_norm: 0.5
minibatch_size: 1920
norm_adv: true
num_envs: 60
num_iterations: 2604
num_minibatches: 4
num_steps: 128
pretrained: false
recover: false
rules: default
save_steps: 1000000
seed: 20
target_kl: null
torch_deterministic: true
total_timesteps: 20000000
track: true
update_epochs: 4
vf_coef: 0.5
wandb_entity: null
wandb_project_name: blendeRL
